### ISSUE TITLE
使用CQ file URI格式发送图片报错 - 原"如何发送图片"

### ISSUE THREAD

**Issue by Cuiyn** [yyuueexxiinngg/cqhttp-mirai#1]
试图用`CQHTTP`的`CQ码`发送图片时，出现了一系列问题：

- 使用`file URI`格式发送图片，如`[CQ:image,file=file:///xxx/xxx/xxx.jpg]`，`Mirai`报如下错误：
` 17:41:29 [ERROR] [CQHTTPMirai] java.lang.IllegalArgumentException: message is empty
        at net.mamoe.mirai.qqandroid.contact.FriendImpl.sendMessage(FriendImpl.kt:89)
...`

- 使用`base64`发送图片，如来自`CQHTTP`官方示例的`[CQ:image,file=base64://iVBORw0KGgoAAAANSUhEUgAAABQAAAAVCAIAAADJt1n/AAAAKElEQVQ4EWPk5+RmIBcwkasRpG9UM4mhNxpgowFGMARGEwnBIEJVAAAdBgBNAZf+QAAAAABJRU5ErkJggg==]`，`Mirai`未报错，但QQ不能正常显示（提示“图片已过期”）

- 使用`HTTPS`链接发送图片，如`[CQ:image,file=https://i.loli.net/2020/05/28/uKvIAWadFC3csPO.jpg]`，`Mirai`报如下错误：
`18:00:22 [ERROR] [CQHTTPMirai] java.io.IOException: Server returned HTTP response code: 403 for URL: https://i.loli.net/2020/05/28/uKvIAWadFC3csPO.jpg
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
...`

看了项目源码，感觉是支持`CQ码`发送图片的，请问我哪里存在错误，应该如何使用？
提前感谢帮助！

**Comment by yyuueexxiinngg** [comment]
用[py-ciohttp](https://github.com/cqmoe/python-aiocqhttp)测试了一下

使用file url发送失败且报相同错误, 但是base64和https均成功, 可以请问下您的测试环境吗?

![image](https://user-images.githubusercontent.com/20928306/83136103-81134700-a119-11ea-94a5-58f92e997f7e.png)

**Comment by Cuiyn** [comment]
感谢您的测试与回复！

这边使用的是[nonebot](https://nonebot.cqp.moe)，据其[文档](https://nonebot.cqp.moe/guide/)，其底层同样使用`py-ciohttp`，感觉与您的环境是类似的；代码附在下面：

```python3
@on_command('发送图片')
async def _(session: CommandSession, only_to_me=False):
    msg = '[CQ:image,file=https://i.loli.net/2020/05/28/uKvIAWadFC3csPO.jpg]'
    await session.send(msg)
```

使用`wget`命令能够正常下载到这张图片；如果问题不能重现，我认为应该是自身环境的问题，这边会继续排查一下。

最后再次感谢您带来了如此优秀的项目！

**Comment by yyuueexxiinngg** [comment]
`cphttp-mirai`的配置文件`setting.yaml`的第一行可加入配置`debug`属性来log接受到的请求, 或许可以提供一些思路

```yaml
debug: true
1234567890:
   ......
```


经测试`Nonebot`亦可正常发送, 测试`mirai`版本为1.0.1,  `mirai-console`版本为0.5.2, `cqhttp-mirai`版本为0.1.2

![image](https://user-images.githubusercontent.com/20928306/83149068-449d1680-a12c-11ea-9bd3-b8faac75db90.png)

**Comment by Cuiyn** [comment]
与您环境相同，目前还未能确定产生`403`错误的原因。

注意到使用`Python`的`urllib`不能直接下载图片（同样产生`403`错误），但是设置请求的`Header`为任意值后就可以了。由此猜想可能是触发了相关服务的反爬虫机制，IP受到限制。小图片下载并使用`Base64`编码后可以正常发送。

谢谢您的测试！
