### ISSUE TITLE
请问支cqhttp-mirai支持coolq-http-api 的事件过滤器吗？

### ISSUE THREAD

**Issue by PiPiSenLetsGo** [yyuueexxiinngg/cqhttp-mirai#101]
我的事件处理用的nonebot，因为不想把所有的消息事件都传给nonebot判断，所以想通过事件过滤器只处理有用的信息。

**Comment by PiPiSenLetsGo** [comment]
coolq-http-api 的事件过滤器
https://richardchien.gitee.io/coolq-http-api/docs/4.15/#/EventFilter

**Comment by wdvxdr1123** [comment]
go-cqhttp已支持（逃）
