### ISSUE TITLE
cqhttp-mirai的编译环境

### ISSUE THREAD

**Issue by Ace-Monster** [yyuueexxiinngg/cqhttp-mirai#11]
感谢大神开发的cqhttp转mirai的插件！
没有看到已发布的JAR包，自己在使用Gradle+JDK1.8编译的时候出了问题：
build.gradle.kts:81:30: Unresolved reference: transferTo
还请告知解决方法，谢谢！

**Comment by Android-KitKat** [comment]
我自己编译时也出现了这个错误。

发布的JAR文件可以在插件中心下载。
https://github.com/project-mirai/mirai-plugins

> Mirai 不负责这些插件的审核或维护，因此，使用前请自行判断是否安全，遇到问题时请联系插件原作者。

**Comment by yyuueexxiinngg** [comment]
此方法在Java 9引入, 使用JDK1.9之后版本试试
[https://docs.oracle.com/javase/10/docs/api/java/io/InputStream.html#transferTo(java.io.OutputStream)](https://docs.oracle.com/javase/10/docs/api/java/io/InputStream.html#transferTo(java.io.OutputStream))
