### ISSUE TITLE
反向ws断线后，似乎只能重启mirai来恢复连接

### ISSUE THREAD

**Issue by LittleNightmare** [yyuueexxiinngg/cqhttp-mirai#14]
### 希望增加
1. 多次连接尝试，目前似乎只有一次
2. 手动重连指令
3. 可以给机器人本身发送提示，来显示断开连接重新连接失败
### 重连的日志
```
[0m 16:00:11 [38;5;196m[WARNING][39;49m [CQHTTPMirai] Websocket连接已断开, 将在3秒后重试连接[39;49m
[0m 16:00:15 [38;5;196m[WARNING][39;49m [CQHTTPMirai] Websocket连接出错, 未知错误, 放弃重试连接, 请检查配置正确后重启mirai  Server error(ws://xn--v9x.net:80/ws: 502 Bad Gateway.io.ktor.client.features.ServerResponseException[39;49m
```

**Comment by yyuueexxiinngg** [comment]
其实是有重试连接的, 不过没有将这个Exception写进去, 这个错误应该是服务器端出了问题, 所以没有尝试重连 (
https://github.com/yyuueexxiinngg/cqhttp-mirai/blob/51640a5c98526b0ae4656f49aad9c6d3a331860b/src/main/kotlin/tech/mihoyo/mirai/web/websocket/WebsocketReverseClient.kt#L125-L143

**Comment by LittleNightmare** [comment]
emm好吧 ~~救救小水管吧~~ ~~如果不打算跑路，那~~可以增加一个重连的指令吗，重启重连总觉得有点蛋疼，或者设定一个间隔较长的重连

**Comment by yyuueexxiinngg** [comment]
emmm, 所有Exception都尝试重连了~~比较简单写lol~~, `0.1.8`版本后上线, 目前未Release, 在Github Action里可以下载到
