### ISSUE TITLE
[Question] 请问分享链接如何附带本地图片

### ISSUE THREAD

**Issue by OhnkytaBlabdey** [yyuueexxiinngg/cqhttp-mirai#145]
- onebot-kotlin版本：`onebot-kotlin-0.3.5-all`
- Java版本：16.0.1
- 系统：Windows 10

OneBot v11 [链接分享](https://github.com/botuniverse/onebot/blob/master/v11/specs/message/segment.md#%E9%93%BE%E6%8E%A5%E5%88%86%E4%BA%AB)
```
[CQ:share,url=http://baidu.com,title=百度]
```
其中的image字段是分享链接的封面图片
我输入的文件URI中没有空格和未转义字符，使用的均为正斜线`/`
```
 file:///D:/Ohnkyta/Repositories/OhnkytaBlabdey/SagumeAutomata/ReadMe.assets/logo.jpg
```
发送的链接没有封面图片

后来又尝试网络上的图片，可以正常发送
```
https://ftp.sihaimg.com/wp-content/uploads/2019/08/7307c2ad4579a2a1994f527490224542.jpg
```

**Comment by yyuueexxiinngg** [comment]
分享链接不支持使用本地图片，原理仅是发送`xml`消息，不涉及图片上传，客户端会通过设置的链接加载图片。
