### ISSUE TITLE
[BUG]协议不规范？

### ISSUE THREAD

**Issue by BoBppy** [yyuueexxiinngg/cqhttp-mirai#149]
#一些CQ码会报错，向插件作者反馈说是这边的问题，那边符合onebot标准（

[点歌相关.txt](https://github.com/yyuueexxiinngg/onebot-kotlin/files/7047834/default.txt)
[ban相关_文本(2021-08-25 223749).txt](https://github.com/yyuueexxiinngg/onebot-kotlin/files/7047835/ban._.2021-08-25.223749.txt)

#### 复现

点歌用到的audio报错
解除禁言时group_ban报错

#### 版本
onebot-`mirai`- `0.3.5` 

b38b44304a6fa370536c48a6cb59798931e7df14

mirai-core-`2.7-RC`   

mirai-console-`2.7-RC`

mirai那边这两个简单的API还是支持的，所以应该不是mirai的问题（

**Comment by yyuueexxiinngg** [comment]
嗯，漏掉了 [音乐自定义分享](https://github.com/botuniverse/onebot-11/blob/master/message/segment.md#%E9%9F%B3%E4%B9%90%E8%87%AA%E5%AE%9A%E4%B9%89%E5%88%86%E4%BA%AB)

**Comment by yyuueexxiinngg** [comment]
解除禁言的问题是`mirai`的`api`有变化，修了
