### ISSUE TITLE
发送长度大于876字节的消息时报错

### ISSUE THREAD

**Issue by shirokurakana** [yyuueexxiinngg/cqhttp-mirai#17]
nonebot使用反向ws连接cqhttp，发送长度大于876字节（876个ascii字符或292个汉字）的消息时抛出如下异常
![Z7`TYTRSX8O3_ZYV_@WR_X0.png](https://i.loli.net/2020/08/02/B6DgaLnvMfie2OV.png)
消息长度：
```python
len(string.encode('utf-8'))
```
另：如果一条消息中既有图片又有文字，则单个图片占用248字节（即只剩下627字节可用于文本）（未测试一条消息中包含多个图片的情况）

**Comment by takayama-lily** [comment]
mirai私聊不支持长消息，群聊可以
