### ISSUE TITLE
file url scheme支持错误导致无法使用CQ码发送本地图片

### ISSUE THREAD

**Issue by Faultiness** [yyuueexxiinngg/cqhttp-mirai#18]
- 环境：Ubuntu 18.04, Java 8 OpenJDK (amd64), Python 3.6.9
- 链接方式：反向ws

文字回复正常，但使用CQ码发送本地图片出错，debug日志如下：
![图片](https://user-images.githubusercontent.com/12472447/89261788-3fdf6c00-d661-11ea-8989-fd709fefe7ff.png)

对应CQHTTP的plugins内插件代码如下：
![图片](https://user-images.githubusercontent.com/12472447/89261854-5b4a7700-d661-11ea-90bd-74650ed257e0.png)

**Comment by yyuueexxiinngg** [comment]
少了一个`/`吧?  `file=file:///`这是前缀, 再加上`/home/*`就是`file=file:////home/*`, 需要完整的绝对路径

**Comment by conservate-lulu** [comment]
同问

**Comment by Faultiness** [comment]
> 
> 
> 少了一个`/`吧? `file=file:///`这是前缀, 再加上`/home/*`就是`file=file:////home/*`, 需要完整的绝对路径

确实是这个原因 改成file:////home/...就可以了。
（不过在酷Q的CQHTTP插件和go-cqhttp中file:///home/...也可
感谢作者指点，同时怒赞优秀插件😁

**Comment by yyuueexxiinngg** [comment]
Fixed in https://github.com/yyuueexxiinngg/cqhttp-mirai/commit/79ae690ad65cfefc79bb6477fc8711a49220a792
