### ISSUE TITLE
install CQHTTPMirai failed

### ISSUE THREAD

**Issue by bj600800** [yyuueexxiinngg/cqhttp-mirai#2]
server reeturned HTTP response cod:502 for URL: https://pan.jasonczc.cn/?/mirai/plugins/CQHTTPMirai/CQHTTPMirai-0.1.3.mp4

**Comment by yyuueexxiinngg** [comment]
jasonczc的服务器问题, 跟本项目无关, 可以在[mirai-plugins](https://github.com/mamoe/mirai-plugins/tree/master/CQHTTPMirai)或者[releases](https://github.com/yyuueexxiinngg/cqhttp-mirai/releases)下载最新jar包

**Comment by bj600800** [comment]
非常感谢您的回复。
已在https://github.com/yyuueexxiinngg/cqhttp-mirai/releases/download/0.1.3/cqhttp-mirai-0.1.3-all.jar下载到jar包，但是java -jar cq* ，提示没有主清单属性。再次感谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yyuueexxiinngg"<notifications@github.com&gt;; 
发送时间: 2020年6月4日(星期四) 上午9:17
收件人: "yyuueexxiinngg/cqhttp-mirai"<cqhttp-mirai@noreply.github.com&gt;; 
抄送: "dzx"<bj600800@vip.qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yyuueexxiinngg/cqhttp-mirai] install CQHTTPMirai failed (#2)





 
jasonczc的服务器问题, 跟本项目无关, 可以在mirai-plugins或者releases下载最新jar包

**Comment by yyuueexxiinngg** [comment]
请将下载到的插件```jar```包放至```mirai```目录下的```/plugins```文件夹中后照常启动```mirai-console-wrapper```

**Comment by bj600800** [comment]
借此机会，初学Linux。
感谢大佬的帮助以及无私奉献。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yyuueexxiinngg"<notifications@github.com&gt;; 
发送时间: 2020年6月4日(星期四) 上午9:27
收件人: "yyuueexxiinngg/cqhttp-mirai"<cqhttp-mirai@noreply.github.com&gt;; 
抄送: "dzx"<bj600800@vip.qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yyuueexxiinngg/cqhttp-mirai] install CQHTTPMirai failed (#2)





 
请将下载到的插件jar包放至mirai目录下的/plugins文件夹中后照常启动mirai-console-wrapper
