### ISSUE TITLE
获取的群成员列表中似乎没有bot自己

### ISSUE THREAD

**Issue by takayama-lily** [yyuueexxiinngg/cqhttp-mirai#23]
这个与原版cqhttp有差异。
另（mirai-native-cqhttp中也没有，go-cqhttp中有，也许是mirai-core不支持）

**Comment by yyuueexxiinngg** [comment]
mirai-core给出的群成员列表没有Bot
https://github.com/mamoe/mirai/blob/master/mirai-core/src/commonMain/kotlin/net.mamoe.mirai/contact/Group.kt#L93-L97

**Comment by takayama-lily** [comment]
现在如何获取机器人在群里的权限呢，以前都是用群成员列表里bot的role获取的

**Comment by takayama-lily** [comment]
感觉GetGroupMemberInfo能获取到。
这个issue如果方便修改的话，还是希望可以修改的，可以和原版完全一致。
不方便的话应该也没啥大问题。

**Comment by yyuueexxiinngg** [comment]
返回值中已添加Bot自身
