### ISSUE TITLE
富文本 content 未转义导致 cqhttp 客户端可能产生解析问题

### ISSUE THREAD

**Issue by zkonge** [yyuueexxiinngg/cqhttp-mirai#26]
https://github.com/yyuueexxiinngg/cqhttp-mirai/blob/e681eeddce41442d099eb46aa5a39a9432587c24/src/main/kotlin/tech/mihoyo/mirai/data/common/MessageDTO.kt#L79

`content` 可能包含 `[`, `]`, `,` 等字符，cqhttp客户端解析时会出现一些问题（比如 QQ 的小程序传来的就是一个 json，里面的逗号会干扰 CQ 码解析）

修复建议：转义

同时建议排查处理 `Message.toCQString()` 中其他类型的消息，同样可能包含需要转义的字符

https://github.com/yyuueexxiinngg/cqhttp-mirai/blob/4c96097a71b4a9c78bf6057b55a2b537c1ec2fbe/src/main/kotlin/tech/mihoyo/mirai/util/CQMessgeParser.kt#L270
（吐槽：这里写了没用上吗

**Comment by yyuueexxiinngg** [comment]
确实没考虑到转义问题
(后面代码是抄来的...捂脸
