### ISSUE TITLE
处理一次消息，反向ws就断开一次

### ISSUE THREAD

**Issue by yimo0908** [yyuueexxiinngg/cqhttp-mirai#27]
![image](https://user-images.githubusercontent.com/53830825/89675512-a0e69880-d91c-11ea-87a5-f63036ed406b.png)

**Comment by yyuueexxiinngg** [comment]
测试无法复现, 请问详细的测试环境?

**Comment by yimo0908** [comment]
win环境下，miraiOK直接运行，只加载了cqhttp-mirai插件

  ws_reverse:
    - enable: true 
      postMessageFormat: string
      reverseHost: bot.pencilss.top
      reversePort: 80
      reversePath: /ws
      useUniversal: true
      reconnectInterval: 50
      accessToken: "081719"

**Comment by yimo0908** [comment]
查出来了，是反向ws上游的问题，抱歉打扰了
