### ISSUE TITLE
更多登陆方式

### ISSUE THREAD

**Issue by lz1998** [yyuueexxiinngg/cqhttp-mirai#30]
- 环境变量

Docker使用更方便
```bash
docker run -it -e ACCOUNT=xxx -e PASSWORD=xxx -e WS_URL="ws://1.2.3.4:8081/ws/universal/" lz1998/spring-cq-client
```

- 参数

bash脚本更方便
```bash
mycli -u用户名 -p密码
```

**Comment by yyuueexxiinngg** [comment]
传参登录可以添加，插件配置暂不考虑

**Comment by lz1998** [comment]
> 传参登录可以添加，插件配置暂不考虑

环境变量也考虑一下？

```kotlin
    val account = System.getenv("ACCOUNT")
    val password = System.getenv("PASSWORD")
```

优先级：传参>环境变量>输入指令

**Comment by yyuueexxiinngg** [comment]
> 传参登录可以添加，插件配置暂不考虑

啊，表达错了，环境变量会支持的

**Comment by yyuueexxiinngg** [comment]
- 可传参 `--account 1234567890 --password xxxxxx`
- 可设环境变量 `cqhttp.account`, `cqhttp.password`, 这里参考了`mirai-console-wrapper`使用小写
- 可读取miraiOK生成的config.txt文件命令
