### ISSUE TITLE
使用nonebot，无法收到请求消息

### ISSUE THREAD

**Issue by ly1102** [yyuueexxiinngg/cqhttp-mirai#34]
好友请求、群请求、群邀请在nonebot都无法收到。但是通过ws正向连接调试看到插件是可以正常处理这类消息的。

**Comment by yyuueexxiinngg** [comment]
Should be fixed in https://github.com/yyuueexxiinngg/cqhttp-mirai/commit/e7a47bc5675c1d90f24040d1f791c613329b55f0
