### ISSUE TITLE
音乐分享 XML 消息在好友发送正常，但在群大概率不正常

### ISSUE THREAD

**Issue by BFvX** [yyuueexxiinngg/cqhttp-mirai#40]
一开始认为是Mirai的问题，因此在mamoe/mirai提了issue：
[https://github.com/mamoe/mirai/issues/492](url)
现经提示，可能是CQHTTPMirai的问题（或我的问题）
限于个人水平不能完全看懂源码……

现在主要想请教发送失败情况下`"message_id":-1`的含义以及可能的原因
以及另一位用户 @ls148478 提及的
> 我是用kt写的 我看了你的那个问题 原因是开头service不对 他不是60 他应该和下面的xml代码中的serviceID相同 所以他应该=2 我不清楚cqhttp应该怎么写 但是问题应该就是这个 因为当初我也遇到过

是否与这相关

**Comment by yyuueexxiinngg** [comment]
请给出发送给`CQHTTPMirai`的消息, 我这边测试下

**Comment by hidden-city** [comment]
我的机器人回复任何内容的消息时都这样。
具体表现为：
每次刚登陆时能在群里正常回复消息，过一小段时间之后消息就发不出来。机器人控制台有显示机器人发送的内容，但下一条[DEBUG]信息的“message_id=-1”。
另外，我的机器人还一会儿一掉线，最常见的掉线时间间隔是16m40s（1000秒整）。和 #35 的问题很类似。
每次掉线自动重连后，机器人都能用一会儿，然后瘫痪一会儿，掉线后又能用一会儿……

**Comment by BFvX** [comment]
> 请给出发送给`CQHTTPMirai`的消息, 我这边测试下

` 10:46:00 [DEBUG] [CQHTTPMirai] {"action":"send_msg","params":{"group_id":123456,"user_id":123456789,"message_type":"group","message":"[CQ:music,type=qq,id=217551140]"},"echo":{"seq":6}}`

但刚才测试又是正常的……现在在尝试能否复现，感觉可以暂时Close了……

不过还有一个小问题就是分享后点播放按钮不能直接播放（

**Comment by yyuueexxiinngg** [comment]
测试正常, 考虑是否为风控
