### ISSUE TITLE
Websocket 支持心跳事件

### ISSUE THREAD

**Issue by yimo0908** [yyuueexxiinngg/cqhttp-mirai#41]
环境信息
cqhttp-mirai版本: 0.2.1
运行环境: windows server 2012+miraiOK win 386
连接方式: 反向WS

bug内容
反向ws链接没有heartbeat，长时间无指令上报后容易断开,只有在重启miraiOK才开始尝试重连（有时候也会触发自动重连，但有时候不会），且这条指令不会被上报。
确定bot没有被屏蔽，没有掉线，其他插件运行正常。

**Comment by ly1102** [comment]
我也遇到了这个问题，一般出现在睡觉起床以后

**Comment by yyuueexxiinngg** [comment]
https://github.com/yyuueexxiinngg/cqhttp-mirai/commit/e66bb74937607518217cad7df702810687bca7e8
