### ISSUE TITLE
可否支持多Bot账号连接同一个正向WS地址？

### ISSUE THREAD

**Issue by maxesisn** [yyuueexxiinngg/cqhttp-mirai#46]
在当前的0.2.1(embedded)版本中，使用CQHTTPMirai支持的多账户配置，配合mirai的多账户登录功能，可以成功使多个账号连接同一个反向WS插件，但对于正向WS则不行，第二个登录的账号会在登录成功后报错"Address already in use"，无法与第一个账号登录时连接上的正向WS插件通信。考虑到多个账号的连接都是由同一个CQHTTPMirai插件进行处理的，请问是否有可能使多个账号同时连接同一个正向WS地址？

**Comment by yyuueexxiinngg** [comment]
此需求与原来的`cqhttp协议`以及现在的`onebot标准`不兼容, 没有在`API`上区分不同账号的方式
