### ISSUE TITLE
Http方式返回的内容有错误

### ISSUE THREAD

**Issue by LambdaYH** [yyuueexxiinngg/cqhttp-mirai#48]
在私聊中使用Http方式连接时，似乎只会复读通过http上报的指令
如图，聊天窗口发送命令
![image](https://user-images.githubusercontent.com/13503375/90769973-ad5af000-e323-11ea-8666-7832b339f910.png)
可以看到响应的内容是正常的，但是返回给聊天窗口的内容是原指令的复读。
群聊~则正常~中有些会复读而有些不会复读
![image](https://user-images.githubusercontent.com/13503375/90774835-a8e60580-e32a-11ea-9b13-be0419c32ee1.png)

环境 :
 `cqhttp-mirai-0.2.2`
 ` mirai-core-qqandroid-1.2.1`
 `mirai-console-0.5.2`

**Comment by yyuueexxiinngg** [comment]
已发修复包
