### ISSUE TITLE
[Feature]支持在header中使用token和用json传递参数

### ISSUE THREAD

**Issue by BaconPapa** [yyuueexxiinngg/cqhttp-mirai#68]
目前 `Authorization: Bearer xxx` 这样的形式传递token会被识别为无效（返回403）

post请求把参数通过json传递服务端会报错

**Comment by yyuueexxiinngg** [comment]
请问使用的`CQHTTPMira`版本, 目前版本这些问题都已经修复 (理论上

**Comment by BaconPapa** [comment]
0.2.0的，关闭了吧orz
