### ISSUE TITLE
能否支持http api或者正向websocket服务？

### ISSUE THREAD

**Issue by muyuqingqiu** [yyuueexxiinngg/cqhttp-mirai#7]
使用koishi开发的程序，切换到miria后恰好没有http api或者正向websocket服务，头疼

**Comment by yiyione** [comment]
我记得todo list 里面是有这个 feature的，不知道做完了没。
我反正是直接改成了用 mirai 的 mirai-api-http ……

**Comment by yyuueexxiinngg** [comment]
- [x] 正向Websocket服务
- [ ] HTTP API
