### ISSUE TITLE
[BUG] 多次发送图片，导致机器人挂掉

### ISSUE THREAD

**Issue by hy353** [yyuueexxiinngg/cqhttp-mirai#75]
机器人刚启动的几分钟内，发送图片是可以的。当发送的图片次数超过了两次，机器人就无响应了。

```



```

#### 版本
cqhttp-mirai-0.2.2.5 ` ` 

mirai-core-qqandroid-1.2.2` `   

mirai-console-0.5.2` `

**Comment by hy353** [comment]
![截屏2020-08-27 下午5 04 46](https://user-images.githubusercontent.com/64407319/91420537-69b63800-e887-11ea-951a-42c93de99612.png)

这是请求截图，获取了接口的返回。第一次发图片，还是有返回的。三分钟后，再次请求发送图片。机器人就无响应了。

**Comment by z924263634** [comment]
可以分享一下jar包吗，我的打包一直有问题

**Comment by yyuueexxiinngg** [comment]
无法复现, 是否有`cqhttp-mirai`的log

**Comment by hy353** [comment]
> 无法复现, 是否有`cqhttp-mirai`的log

我使用MiraiOk运行的。没看到有日志输出。在windows环境已命令行运行的。

可能是不兼容吧。已经让专门的java开发人员去看了。难受。

**Comment by hy353** [comment]
> 可以分享一下jar包吗，我的打包一直有问题

我用MiraiOk运行的。

**Comment by yyuueexxiinngg** [comment]
> 我使用MiraiOk运行的。没看到有日志输出。在windows环境已命令行运行的。

`miraiOK`目前启动的`mirai-core`版本为`1.1.3`, `cqhttp-mirai 0.2.2`以上版本最低要求`mirai-core`版本为`1.2.0`
