### ISSUE TITLE
[BUG] ubuntu18下  0.2.3启动报错

### ISSUE THREAD

**Issue by klarkxy** [yyuueexxiinngg/cqhttp-mirai#77]
使用0.2.3的all.jar就会报这个错误
但使用0.2.1的就不会
是我环境没有配置好么？
安装流程是根据这个来的
https://yobot.win/install/Linux-cqhttp-mirai/

环境：ubuntu 18

```
![image](https://user-images.githubusercontent.com/6316992/91433701-43e45f80-e896-11ea-8a09-54aa9b2f3bae.png)



```

#### 版本
cqhttp-mirai-0.2.3-all.jar 

mirai-core-qqandroid-1.1.3.jar

mirai-console-0.5.2.jar

**Comment by yyuueexxiinngg** [comment]
Duplicate of #73
