### ISSUE TITLE
Mirai客户端吞消息，另外发送的语音手机上可听电脑上不可听

### ISSUE THREAD

**Issue by planevina** [yyuueexxiinngg/cqhttp-mirai#82]
最近发现Mirai会吞消息，在console窗口内显示消息已经发出，但是实际上并没有发出。
测试是当汉字组合达到一些特定顺序后，就无法发出。
比如PCR的查刀，也许还剩9个人的时候，就能发送消息，还剩8个人，消息就被吞了
也比如我自己做的其他功能，我发送文字组1、2，能发送，发送文字组2、3，能发送
但是发送文字组1、2、3一起，或者1、3，消息就发不出来
我确信，仔细检查过，没有任何违规，屏蔽等等不合法的文字，都是正常文字。
很抱歉用了这么啰嗦的文字来形容这个问题，但是这问题确实就是这么费解。。。会不会是unicode？什么的问题？
~~~~~~~~~~~~~~~~~~~~~~
另外一个小问题，用Embedded分支版本发送语音，格式为mp3，手机上能听，电脑上无声，不知道为啥。
~~~~~~~~~~~~~~~~~~~~~~~
感谢你们的贡献，谢谢！

**Comment by yyuueexxiinngg** [comment]
第一个应该是`mirai`本身的问题, 请在`mirai`方开Issue

第二个, PC上要是能听, 只能发`amr`或者`silk`格式的

**Comment by planevina** [comment]
> 第一个应该是`mirai`本身的问题, 请在`mirai`方开Issue
> 
> 第二个, PC上要是能听, 只能发`amr`或者`silk`格式的

多谢！
