### ISSUE TITLE
[Feature] 新的 option: --init 生成基本结构

### ISSUE THREAD

**Issue by lengthmin** [yyuueexxiinngg/cqhttp-mirai#88]
现在的逻辑是第一次启动没有文件结构的话就生成文件结构，如果有办法直接有个参数 --init 生成文件结构就好了。
比如想放在 Docker 中运行，可以在 Dockerfile 中先生成好基本结构，然后做对应的修改即可，而不是自己手动创建一个文件内容再复制过去。

**Comment by yyuueexxiinngg** [comment]
是指生成配置文件吗?  目前的生成逻辑基于`mirai-console`本身的序列化和存储, 没有计划额外添加支持
