### ISSUE TITLE
[Feature] config.txt 格式优化

### ISSUE THREAD

**Issue by lengthmin** [yyuueexxiinngg/cqhttp-mirai#89]
现在是寻找 --- 行，而且 `-` 的字符个数都要相等。
https://github.com/yyuueexxiinngg/cqhttp-mirai/blob/embedded/src/main/kotlin/tech/mihoyo/Main.kt#L105

可以直接简化逻辑，比如直接检测不已 `#` 或者 `---` 开头的行都当成命令之类的。

**Comment by yyuueexxiinngg** [comment]
逻辑来自`miraiOK`, 现`miraiOK`已放弃`config.txt`支持, 这边同步取消支持
