### ISSUE TITLE
群管理员权限返回administrator何时release

### ISSUE THREAD

**Issue by benbenlike** [yyuueexxiinngg/cqhttp-mirai#9]
你好，为了和cqhttp表现一致，群管理的role返回的应该是admin，实际使用过程中发现返回administrator。然后发现该问题修复其实已经早就修复，但是是在0.1.4release之后修复的，最新release的0.1.4的jar包还是旧的。请问何时release？

**Comment by yyuueexxiinngg** [comment]
Release了 (
