### ISSUE TITLE
[BUG]get_group_member_list API 入群时间、年龄等信息都是0

### ISSUE THREAD

**Issue by jiangjiangflies** [yyuueexxiinngg/cqhttp-mirai#91]
获取群成员列表，性别、入群时间、年龄等都获取失败！
"sex":"unknown","age":0,"join_time":0,"last_sent_time":0

版本CQHTTP Mirai 0.2.3,mirai-console-0.5.2

**Comment by yyuueexxiinngg** [comment]
`mirai`不支持获取这些资料

> 特别注意, 很多信息Mirai不支持获取, 如群成员的年龄、性别等, 为保证兼容性, 这些项已用Unknown, 0之类的信息填充占位
