### ISSUE TITLE
[Question]CQHTTP Mirai 0.2.3 搭配的mirai console 和 core的版本最好是

### ISSUE THREAD

**Issue by asdMild** [yyuueexxiinngg/cqhttp-mirai#93]
CQHTTP Mirai 0.2.3 搭配的mirai console 和 core的版本最好是哪个版本  用miraiOK会不会有问题，纯粹只想运行一个  cqhttp

**Comment by Mateoust** [comment]
> CQHTTP Mirai 0.2.3 搭配的mirai console 和 core的版本最好是哪个版本 用miraiOK会不会有问题，纯粹只想运行一个 cqhttp

CQHTTP Mirai 0.2.3用最新版本的MiraiOK吧。老版本MiraiOK的core和console只能用到CQHTTP Mirai 0.2.1

**Comment by Yprolic** [comment]
mirai-console-1.0-M4-dev-3-all.jar

**Comment by Yprolic** [comment]
console M4大概不支持，我这边测了，无法加载，你可以用M3试试

**Comment by asdMild** [comment]
我现在用的console  0.5.2  +  mirai cor qq 1.1.3 + CQHTTP Mirai 0.2.1 还算稳定   等后续有版本了在测试其他的
