### ISSUE TITLE
[BUG][Embedded]当plugins文件夹中有任何可用插件时不读取setting.yml

### ISSUE THREAD

**Issue by Cursor-S** [yyuueexxiinngg/cqhttp-mirai#95]
当plugins文件夹中有任何可用插件时，启动的时候不读取setting.yml并返回未配置

```
[DEBUG] [CQHTTPMirai] 26******71未对CQHTTPMirai进行配置
```
#### 复现

- 往plugins文件夹中塞一个插件
- 启动 控制台返回【加载1个插件】
- 控制台返回【未对CQHTTPMirai进行配置】
#### 版本
cqhttp-mirai- `0.2.3-embedded`

**Comment by yyuueexxiinngg** [comment]
Duplicate of #49

**Comment by yyuueexxiinngg** [comment]
abc4dd1fc2181339e814fa8f2633d3f2eb27be3c
