### ISSUE TITLE
[BUG] 2.3.0版本插件无法被console-1.0-M4检测到

### ISSUE THREAD

**Issue by SplendarA** [yyuueexxiinngg/cqhttp-mirai#99]
在CentOS 7.5（64位）下，使用更新至console-1.0-M4的miraiOK无法检测到2.3.0版本的cqhttp插件（非embedded版本）。
已向mirai项目提出该问题，得到回复为插件未适配新版console插件检测机制，请确认。
详见https://github.com/mamoe/mirai-console/issues/181

**Comment by XZhouQD** [comment]
我暂时做了一个自行修改版，一个融合怪（启动方式是1.0-M4的，配置文件部分为了不重写，把0.5.2的API打进了包里），在 [XZhouQD/cqhttp-mirai/Release](https://github.com/XZhouQD/cqhttp-mirai/releases/tag/0.2.4-SNAPSHOT-1.0-M4)

请注意这个版本是我自行修改，不保证是否出问题，可以在1.0-M4启动。真正的0.2.4应该等作者认为合适的时机将插件重构到Console 1.0的API，而不是我这样的融合怪能启动就行

**Comment by yyuueexxiinngg** [comment]
`dev`分支已完成适配, 近期测试后将发布
